version: "3"
services:
  redis:
    image: redis:5.0-alpine
    ports:
      - "6379"
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis:6379/0
