name: Docker Image CI

on:
  push:
    branches: [ master ]


jobs:

  build:

    runs-on: ubuntu-latest
    env:
      DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD }}
    steps:
    - uses: actions/checkout@v2
    - name: Docker login
      run: echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_USER --password-stdin $DOCKER_REGISTRY
    - name: Build the Docker image
      run: |        
        docker build . --file Dockerfile --tag $DOCKER_REGISTRY/$DOCKER_USER/infra-app:latest
        docker tag $DOCKER_REGISTRY/$DOCKER_USER/infra-app:latest $DOCKER_REGISTRY/$DOCKER_USER/infra-app:$(git rev-parse --short HEAD)
    - name: Docker push images
      run: |
        docker push $DOCKER_REGISTRY/$DOCKER_USER/infra-app:$(git rev-parse --short HEAD)
        docker push $DOCKER_REGISTRY/$DOCKER_USER/infra-app:latest
